# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 12) do

  create_table "authors", :force => true do |t|
    t.column "name",     :string
    t.column "bio",      :text
    t.column "story_id", :string
    t.column "email",    :string
  end

  create_table "libraries", :force => true do |t|
  end

  create_table "stories", :force => true do |t|
    t.column "title",     :string
    t.column "maintext",  :text
    t.column "rundate",   :date
    t.column "blurb",     :text
    t.column "author_id", :string
    t.column "appeared",  :text
  end

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
  end

end
